name: Nightly PKG

on:
  workflow_dispatch:
  push:
  
jobs:
  macOS:
    name: test
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          #- { os: macos-10.15, xcode: 11.3.1, deployment: 10.7 }
          - { os: macos-10.15, xcode: 11.7,   deployment: 10.14 }
          - { os: macos-10.15, xcode: 12.4,   deployment: 10.15 }
          - { os: macos-11,    xcode: 12.5.1, deployment: 11.3 }
        compiler:
          - { compiler: XCode,   CC: cc, CXX: c++ }
        btype: [ RelWithDebInfo ]
        target:
          - skiptest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.build.xcode }}.app/Contents/Developer
      CC: ${{ matrix.compiler.CC }}
      CXX: ${{ matrix.compiler.CXX }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.build.deployment }}
      CXXFLAGS: -stdlib=libc++
      OBJCXXFLAGS: -stdlib=libc++
      SRC_DIR: ${{ github.workspace }}/src
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_PREFIX: ${{ github.workspace }}/install
      CMAKE_BUILD_TYPE: ${{ matrix.btype }}
      #GENERATOR: Ninja
      GENERATOR: Unix Makefiles
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src
      - name: Install Base dependencies
        run: brew install glib
      - name: Compile and install lensfun
        run: |
          wget https://github.com/lensfun/lensfun/archive/refs/tags/v0.3.2.tar.gz -O lensfun-v0.3.2.tar.gz
          tar xzf lensfun-v0.3.2.tar.gz
          cd lensfun-0.3.2
          mkdir cmake_build && cd cmake_build
          cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/lensfun
          export LIBRARY_PATH="$LIBRARY_PATH:`brew --prefix`/lib"
          make
          sudo make install
      - name: Update lensfun data
        run: |
          export PATH=$PATH:/opt/lensfun/bin
          export PYTHONPATH=/opt/lensfun/lib/python3.9/site-packages/
          echo PPath: $PYTHONPATH

          head -n 20 /opt/lensfun/lib/python3.9/site-packages/lensfun/__init__.py

          echo "lensfun-update-data is here:"
          echo `which lensfun-update-data`

          echo "--- head of lensfun-update-data ---"
          head `which lensfun-update-data`
          echo "--- end ---"

          sudo lensfun-update-data
